version: '3.8'

services:
  cloud_backend:
    container_name: cloud_backend
    image: ${DOCKER_USER}/cloud-backend:latest
    build:
      context: ./cloud-core
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - PORT=4002
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - cloud_uploads:/app/uploads
    restart: always
    networks:
      - cloud_network
      - proxy_network

  cloud_frontend:
    container_name: cloud_frontend
    image: ${DOCKER_USER}/cloud-frontend:latest
    build:
      context: ./cloud-frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - NEXT_PUBLIC_API_URL=http://cloud_backend:4002
    depends_on:
      - cloud_backend
    restart: always
    networks:
      - cloud_network
      - proxy_network

volumes:
  cloud_uploads:
    driver: local

networks:
  cloud_network:
    driver: bridge
  proxy_network:
    external: true
