version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cloud_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cloud_user
      POSTGRES_PASSWORD: cloud_password
      POSTGRES_DB: cloud_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud_network

  # Opcional: PgAdmin para gerenciar o banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cloud_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cloud.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - cloud_network

volumes:
  postgres_data:
    driver: local

networks:
  cloud_network:
    driver: bridge
