name: Deploy Pickbox

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./pickbox-core
          file: ./pickbox-core/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pickbox-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/pickbox-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USER }}/pickbox-backend:buildcache,mode=max

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./pickbox-frontend
          file: ./pickbox-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pickbox-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/pickbox-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USER }}/pickbox-frontend:buildcache,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/pickbox
            docker-compose pull
            docker-compose up -d
            docker image prune -f
